import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: "100%",
  },
  carouselContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  arrowButton: {
    backgroundColor: "rbg(0, 0, 0)",
    alignItems: "center",
    justifyContent: "center",
    width: 50,
  },
  arrowText: {
    color: "#fff",
    fontSize: 30,
    fontWeight: "bold",
  },
  disabledArrow: {
    color: "rgba(0, 0, 0, 0)", 
  },
  interpretationText: {
    fontSize: 16,
    color: "#333",
    textAlign: "center",
  },
  similarDreamsContainer: {
    height: 170,
    marginTop: 20,
    marginBottom: 50,
    paddingHorizontal: 10,
    borderTopWidth: 1,
    borderTopColor: "#fff",
    paddingTop: 15,
  },
  similarDreamsTitle: {
    fontSize: 30,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 10,
    textAlign: "center",
  },
  similarDreamsList: {
    flexDirection: "row",
    width: "100%",
  },
  similarDreamThumbnailContainer: {
    marginRight: 10,
  },
  similarDreamThumbnail: {
    width: 80,
    height: 80,
    resizeMode: "cover",
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#000",
  },
  sceneContainer: {
    flex: 1,
    top: "10%",
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 10,
    paddingHorizontal: 20,
    paddingBottom: 30,
  },
  imageNavigationContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 20,
  },
  sceneImage: { 
    width: 200,
    height: 200,
    resizeMode: "contain",
    borderRadius: 20,
    borderWidth: 3,
    borderColor: "#000",
  },
  interpretationContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    backgroundColor: "rgba(97, 54, 164, 0.4)",
  },
  scrollContainer: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  sceneDescription: {
    fontSize: 20,
    textAlign: "center",
    marginBottom: 10,
    color: "#fff",
    lineHeight: 30,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderColor: "rgba(255, 255, 255, 1)",
  },
  sceneMood: {
    fontSize: 16,
    fontStyle: "italic",
    marginVertical: 10,
    color: "#fff",
    textAlign: "center",
  },
  symbolsTitle: {
    fontSize: 30,
    fontWeight: "bold",
    marginTop: 10,
    marginLeft: 10,
    color: "#fff",
    textAlign: "center",
  },
  symbolItem: {
    marginHorizontal: 10,
    marginTop: 15,
  },
  symbolName: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 5,
  },
  symbolMeaning: {
    fontSize: 16,
    color: "#fff",
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
  },
  navigationContainer: {
   flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    paddingHorizontal: 20,
    marginBottom: 10,
  },
});