import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    width: "100%",
    height: "100%",
  },
  sectionTitle: {
    paddingTop: 100,
    fontSize: 50,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 10,
  },
  toggleButtonsContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginVertical: 10,
  },
  toggleButton: {
    paddingVertical: 8,
    paddingHorizontal: 24,
    borderRadius: 20,
    marginHorizontal: 5,
    borderWidth: 1,
    borderColor: "#351b64",
  },
  toggleButtonActive: {
    backgroundColor: "#fff",
  },
  toggleButtonInactive: {
    backgroundColor: "#351b64",
  },
  toggleButtonText: {
    fontWeight: "bold",
  },
  toggleButtonTextActive: {
    color: "#351b64",
  },
  toggleButtonTextInactive: {
    color: "#fff",
  },
  searchBar: {
    flexDirection: "row",
    width: "80%",
    borderBottomWidth: 1,
    borderColor: "#fff",
    paddingHorizontal: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: "#fff",
    marginHorizontal: 8,
  },
  gridContainer: {
    marginTop: 30,
    alignItems: "flex-start",
    paddingBottom: 10,
    width: "100%",
  },
  dreamThumbnailContainer: {
    flex: 1,
    marginHorizontal: 55,
    marginVertical: 5,
    alignItems: "center",
  },
  dreamThumbnail: {
    width: 100,
    height: 100,
    borderRadius: 10,
    resizeMode: "cover",
    padding: 5,
    borderWidth: 2,
    borderColor: "#000",
  },
  dreamTitle: {
    marginTop: 5,
    fontSize: 12,
    fontWeight: "bold",
    color: "#fff",
    textAlign: "center",
  },
  timelineTime: {
    color: "#fff",
    fontSize: 16,
    width: 73,
  },
  timeline: {
    flex: 1,
    width: "100%",
    alignSelf: "center",
    marginTop: 30,
    marginVertical: 20,
    marginHorizontal: 20,
    paddingHorizontal: 40,
    scrollbarWidth: "none",
  },
  dreamDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    width: "100%",
    paddingVertical: 15,
  },
  dreamImage: {
    width: 70,
    height: 70,
    borderRadius: 10,
    marginRight: 10,
    borderWidth: 2,
    borderColor: "#000",
  },
  loadingContainer: {
    flex: 1,
    paddingTop: 40,
    alignItems: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "#000a",
    justifyContent: "center",
    alignItems: "center",
  },
  modalOverlayTouchable: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 20,
    width: "80%",
    alignItems: "center",
  },
  modalImage: {
    width: 200,
    height: 200,
    borderRadius: 10,
    marginBottom: 10,
    borderWidth: 2,
    borderColor: "#351b64",
  },
  modalTagsContainer: {
    height: 120,
    width: "100%",
  },
  modalTagsScroll: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    paddingVertical: 4,
  },
  modalDescription: {
    fontSize: 16,
    color: "#333",
    marginBottom: 10,
    textAlign: "center",
  },
  modalClose: {
    marginTop: 20,
    paddingVertical: 8,
    paddingHorizontal: 24,
    backgroundColor: "#351b64",
    borderRadius: 20,
  },
  modalCloseText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 20,
    textAlign: "center",
  },
  tag: {
    backgroundColor: "rgb(130, 92, 191)",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    margin: 3,
  },
  tagText: {
    color: "#fff",
    fontSize: 12,
  },
});