import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    width: "100%",
    height: "100%",
  },
  description: {
    fontSize: 32,
    color: "#fff",
    fontWeight: "300",
    textAlign: "center",
    marginHorizontal: 30,
    lineHeight: 45,
    marginTop: 120,
  },
  voice: {
    margin: 25,
  },
  textArea: {
    backgroundColor: "rgba(97, 54, 164, 0.2)",
    width: '80%',
    height: '20%',
    borderWidth: 2,
    borderColor: "#FFF",
    borderRadius: 5,
    margin: 10,
  },
  input: {
    color: "#fff",
    fontSize: 16,
    height: '100%',
    textAlignVertical: "top",
    fontWeight: "300",
    padding: 10,
  },
  continueButton: {
    position: "absolute",
    top: '80%',
  },
  steps: {
    position: "absolute",
    top: '90%',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 20,
    width: "90%",
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
    color: "#351b64",
  },
  modalInput: {
    width: "100%",
    height: 180,
    borderColor: "#351b64",
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    fontSize: 16,
    color: "#222",
    backgroundColor: "#f9f9f9",
    marginBottom: 20,
    textAlignVertical: "top",
  },
  modalButton: {
    backgroundColor: "#351b64",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 30,
  },
  modalButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
});
