import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
    position: 'relative',
    alignItems: 'center',
  },
  rectangle: {
    position: 'absolute',
    width: '100%',
    top: 0,
    left: 0,
  },
  vector: {
    position: 'absolute',
    resizeMode: 'stretch',
    width: '100%',
    top: 150,
    left: 0,
  },
  regMoon: {
    position: 'absolute',
    width: 260,
    height: 260,
    transform: 'rotate(43.49deg)',
    top: -50,
    right: -70,
  },

  logMoon: {
    position: 'absolute',
    width: 260,
    height: 260,
    transform: 'rotate(43.49deg)',
    top: -50,
    left: -100,
  },

  title: {
    position: 'absolute',
    top: 250,
    fontSize: 40,
    fontWeight: '700',
    color: '#351b64',
    marginBottom: 8,
  },
  subtitle: {
    position: 'absolute',
    top: 310,
    fontSize: 18,
    fontWeight: '400',
    color: '#8b8b8b',
  },
  formContainer: {
    position: 'absolute',
    top: 310,
    left: 0,
    width: '100%',
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
    padding: 35,
    paddingTop: 55,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#c3bee9',
    borderRadius: 10,
    marginBottom: 15,
    paddingStart: 15,
    height: 45,
  },
  icon: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    color: '#351b64',
    fontSize: 14,
    fontWeight: '500',
    height: '100%',
    borderRadius: 10,
    paddingStart: 10,
  },
  button: {
    backgroundColor: '#351b64',
    borderRadius: 25,
    marginTop: 20,
    paddingVertical: 13,
    width: '75%',
    alignSelf: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '500',
  },
  linkContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 15,
  },
  linkText: {
    fontSize: 15,
    color: '#8b8b8b',
  },
  link: {
    fontSize: 15,
    color: '#351b64',
    fontWeight: '600',
    marginLeft: 5,
    textDecorationLine: 'underline',
  },
  orContainer: {
    marginTop: 15,
    alignItems: 'center',
    position: 'relative',
    justifyContent: 'center',
  },
  line: {
    width: '100%',
    height: 1,
    backgroundColor: '#c7c7c7',
    position: 'absolute',
    top: 8,
  },
  orTextContainer: {
    backgroundColor: '#fff',
    paddingHorizontal: 10,
    zIndex: 1,
  },
  orText: {
    color: '#6b6b6b',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  authIcons: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
    gap: 20,
  },
  authIconButton: {
    borderColor: '#c7c7c7',
    borderWidth: 1,
    borderRadius: 25,
    padding: 13,
  },
  authIcon: {
    width: 24,
    height: 24,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 5,
  },
  forgotText: {
    color: '#351B64',
    fontSize: 13,
    textDecorationLine: 'underline',
  },
});
